# Generated by Django 4.2 on 2023-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('avaible', 'Disponoble'), ('not avaible', 'No disponible')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='veggie_option',
            field=models.CharField(choices=[('avaible', 'Disponoble'), ('not avaible', 'No disponible')], max_length=15),
        ),
    ]
