# Generated by Django 4.2 on 2023-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(max_length=240)),
                ('price', models.IntegerField()),
                ('available', models.CharField(choices=[('avaible', 'Disponoble'), ('not avaible', 'No disponible')], max_length=15)),
                ('veggie_option', models.CharField(choices=[('avaible', 'Disponoble'), ('not avaible', 'No disponible')], max_length=15)),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='promo/')),
            ],
        ),
    ]
